# Generated by Django 2.1.2 on 2019-03-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_goods', '0002_auto_20181211_2100'),
        ('freshfruit', '0004_auto_20181211_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete='CASCADE', to='df_goods.GoodInfo')),
                ('user', models.ForeignKey(on_delete='"CASCADE"', to='freshfruit.Userinfo')),
            ],
        ),
    ]
