# Generated by Django 2.1.2 on 2018-12-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usename', models.CharField(max_length=20)),
                ('userpwd', models.CharField(max_length=40)),
                ('useremail', models.CharField(max_length=30)),
                ('usretel', models.CharField(max_length=20)),
                ('useraddress', models.CharField(max_length=100)),
                ('youbian', models.CharField(max_length=6)),
            ],
        ),
    ]
