# Generated by Django 2.1.2 on 2018-12-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshfruit', '0002_auto_20181204_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userpwd',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='youbian',
            field=models.CharField(max_length=6),
        ),
    ]
