# Generated by Django 2.1.2 on 2018-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshfruit', '0003_auto_20181204_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='youbian',
            field=models.CharField(default='', max_length=6),
        ),
    ]
