# Generated by Django 2.1.2 on 2018-12-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TyoeInfo',
            new_name='TypeInfo',
        ),
    ]
