# Generated by Django 2.1.2 on 2019-03-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freshfruit', '0004_auto_20181211_2300'),
        ('df_goods', '0002_auto_20181211_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete='CASCADE', to='df_goods.GoodInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('oid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('odata', models.DateTimeField(auto_now=True)),
                ('oIspay', models.BooleanField(default=False)),
                ('ototal', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete='"CASCADE"', to='freshfruit.Userinfo')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete='CASCADE', to='df_order.OrderInfo'),
        ),
    ]
